// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhT5k0f2b72xFGRlUWHm9LHPdtr-JcBHE',
    appId: '1:507195805543:web:b34a9a76ecaf53e70c69c2',
    messagingSenderId: '507195805543',
    projectId: 'slotin-832f6',
    authDomain: 'slotin-832f6.firebaseapp.com',
    storageBucket: 'slotin-832f6.firebasestorage.app',
    measurementId: 'G-71R2HSV8JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGKWbIxY5hLaisNZvKvrit-stGK9-2c8E',
    appId: '1:507195805543:android:d25e92eb1f32b4060c69c2',
    messagingSenderId: '507195805543',
    projectId: 'slotin-832f6',
    storageBucket: 'slotin-832f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABUKGoQ1gtik811EEpB6TkF59w2XyUiG8',
    appId: '1:507195805543:ios:afe9fc59f542f2cc0c69c2',
    messagingSenderId: '507195805543',
    projectId: 'slotin-832f6',
    storageBucket: 'slotin-832f6.firebasestorage.app',
    iosBundleId: 'com.example.slotin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABUKGoQ1gtik811EEpB6TkF59w2XyUiG8',
    appId: '1:507195805543:ios:afe9fc59f542f2cc0c69c2',
    messagingSenderId: '507195805543',
    projectId: 'slotin-832f6',
    storageBucket: 'slotin-832f6.firebasestorage.app',
    iosBundleId: 'com.example.slotin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhT5k0f2b72xFGRlUWHm9LHPdtr-JcBHE',
    appId: '1:507195805543:web:89b2945dd4842bb60c69c2',
    messagingSenderId: '507195805543',
    projectId: 'slotin-832f6',
    authDomain: 'slotin-832f6.firebaseapp.com',
    storageBucket: 'slotin-832f6.firebasestorage.app',
    measurementId: 'G-6SK3H8W8V0',
  );
}
